spring:
  application:
    name: controller
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 6666
    url: jdbc:postgresql://localhost:5432/senla
logging:
  level:
    org:
      springframework:
        context:
          annotation: DEBUG
